### PR TITLE
Align organisation IDs in output

### PR DESCRIPTION
**Pull request by neonichu**

### CODE REVIEW

**Comment by dlitvakb** [comment]
@neonichu using `%` formatting is a style smell

We can change that to:

```ruby
printf "%-20s %s\n", org['name'], org['sys']['id']
```

**Comment by neonichu** [comment]
Opted to use `sprintf` so that we don't have to make structural changes. Would probably make sense to run rubocop on CI to catch such things?

**Comment by neonichu** [comment]
:bell:

**Comment by dlitvakb** [comment]
Can you squash the commits onto 1?

Merging afterwards

**Comment by dlitvakb** [comment]
:+1:

**Pull request merged**
